import React, { useState, useEffect } from "react";

const BASE = "http://localhost:8000/api";

function formatCaseFile(text) {
  if (!text || text === "PENDING") return null;
  // Parse structured markers into sections
  const sections = [];
  const lines = text.split("\n");
  let current = null;

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) continue;
    // Check for bold section headers like **Summary:** or 1. **Summary:**
    const headerMatch = trimmed.match(/^\*\*(.+?)\*\*:?(.*)/);
    const numberedMatch = trimmed.match(/^\d+\.\s+\*\*(.+?)\*\*:?(.*)/);
    const bulletMatch = trimmed.match(/^[-•]\s+(.*)/);

    if (numberedMatch || headerMatch) {
      const title = (numberedMatch || headerMatch)[1].replace(":", "");
      const rest = (numberedMatch || headerMatch)[2]?.trim();
      current = { title, bullets: [], intro: rest || "" };
      sections.push(current);
    } else if (bulletMatch && current) {
      current.bullets.push(bulletMatch[1]);
    } else if (current) {
      if (current.intro) current.intro += " " + trimmed;
      else current.intro = trimmed;
    } else {
      sections.push({ title: "Summary", intro: trimmed, bullets: [] });
      current = sections[sections.length - 1];
    }
  }

  return sections.length > 0 ? sections : null;
}

function CaseSection({ title, intro, bullets }) {
  const icons = {
    "Summary": "🔍",
    "Trigger": "⚡",
    "Key Trigger": "⚡",
    "Behavioral Assessment": "🧠",
    "Risk Classification": "📊",
    "Recommended Action": "📋",
    "Chain Progression": "🔗",
    "Recommendation": "📋",
    "Action": "📋",
  };
  const icon = Object.entries(icons).find(([k]) => title.toLowerCase().includes(k.toLowerCase()))?.[1] || "📌";

  return (
    <div className="flex flex-col gap-1.5">
      <div className="flex items-center gap-2">
        <span className="text-sm">{icon}</span>
        <h4 className="text-xs font-bold text-gray-400 uppercase tracking-wider">{title}</h4>
      </div>
      {intro && <p className="text-sm text-gray-300 leading-relaxed ml-5">{intro}</p>}
      {bullets && bullets.length > 0 && (
        <ul className="flex flex-col gap-1 ml-5 mt-0.5">
          {bullets.map((b, i) => (
            <li key={i} className="flex items-start gap-2 text-sm text-gray-400">
              <span className="text-blue-400 flex-shrink-0 mt-0.5">•</span>
              <span>{b}</span>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}

export default function CaseFileView({ txId }) {
  const [caseFile, setCaseFile] = useState(null);
  const [status, setStatus] = useState("idle"); // idle | loading | ready | pending | error

  useEffect(() => {
    if (!txId) { setCaseFile(null); setStatus("idle"); return; }
    setStatus("loading");
    setCaseFile(null);

    let attempts = 0;
    const maxAttempts = 15;

    const poll = async () => {
      try {
        const res = await fetch(`${BASE}/case/${txId}`);
        const data = await res.json();

        if (data.status === "ready" && data.case_file) {
          setCaseFile(data.case_file);
          setStatus("ready");
        } else if (data.status === "pending" && attempts < maxAttempts) {
          attempts++;
          setStatus("pending");
          setTimeout(poll, 2000);
        } else if (attempts >= maxAttempts) {
          setStatus("error");
        }
      } catch {
        setStatus("error");
      }
    };

    poll();
  }, [txId]);

  return (
    <div className="flex flex-col gap-4">
      {/* Header */}
      <div className="flex items-center gap-2">
        <span className="text-base">🧾</span>
        <h3 className="text-xs font-bold text-gray-400 uppercase tracking-widest">AI Case File</h3>
        {status === "ready" && (
          <span className="ml-auto text-[10px] font-bold text-blue-400 bg-blue-900/30 border border-blue-700/40 px-2 py-0.5 rounded-full">
            GENERATED BY LLM
          </span>
        )}
        {status === "pending" && (
          <span className="ml-auto text-[10px] font-bold text-amber-400 bg-amber-900/30 border border-amber-700/40 px-2 py-0.5 rounded-full animate-pulse">
            GENERATING…
          </span>
        )}
      </div>

      {/* Content */}
      {status === "idle" && (
        <div className="flex flex-col items-center justify-center py-10 text-gray-600 gap-3">
          <span className="text-4xl">📄</span>
          <p className="text-sm">Select a flagged transaction to generate case file</p>
        </div>
      )}

      {status === "loading" && (
        <div className="flex items-center gap-3 px-4 py-4 rounded-xl bg-gray-800/50 border border-gray-700">
          <div className="w-5 h-5 border-2 border-blue-500/50 border-t-blue-400 rounded-full animate-spin flex-shrink-0" />
          <p className="text-sm text-gray-400">Connecting to case file API…</p>
        </div>
      )}

      {status === "pending" && (
        <div className="flex items-center gap-3 px-4 py-4 rounded-xl bg-blue-900/20 border border-blue-700/40">
          <div className="w-5 h-5 border-2 border-blue-500/50 border-t-blue-400 rounded-full animate-spin flex-shrink-0" />
          <div>
            <p className="text-sm font-semibold text-blue-300">AI Analysis in Progress</p>
            <p className="text-xs text-blue-500/70 mt-0.5">Gemini is reviewing transaction patterns…</p>
          </div>
        </div>
      )}

      {status === "error" && (
        <div className="flex items-start gap-3 px-4 py-4 rounded-xl bg-red-900/20 border border-red-800/40">
          <span className="text-xl flex-shrink-0">⚠️</span>
          <div>
            <p className="text-sm font-semibold text-red-300">Case file unavailable</p>
            <p className="text-xs text-red-500/70 mt-0.5">The LLM service may be offline. Check GEMINI_API_KEY in .env</p>
          </div>
        </div>
      )}

      {status === "ready" && caseFile && (() => {
        const sections = formatCaseFile(caseFile);
        return (
          <div className="flex flex-col gap-1">
            <div className="flex items-center gap-2 px-4 py-3 rounded-xl bg-blue-900/20 border border-blue-700/30 mb-2">
              <span className="text-lg">📄</span>
              <div>
                <p className="text-sm font-bold text-blue-300">FRAUD INTELLIGENCE REPORT</p>
                <p className="text-[10px] text-blue-500/70 mt-0.5">Automated analysis by FraudSense AI</p>
              </div>
            </div>
            {sections ? (
              <div className="flex flex-col gap-4 px-1">
                {sections.map((s, i) => <CaseSection key={i} {...s} />)}
              </div>
            ) : (
              <pre className="text-sm text-gray-300 leading-relaxed whitespace-pre-wrap font-sans px-1">
                {caseFile}
              </pre>
            )}
          </div>
        );
      })()}
    </div>
  );
}
